spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: jpetstore-account

  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis